-- Zestaw 10 - Implementacja przykładowej bazy danych
-- Przygotowanie bazy danych
-- Zadanie 1
set echo on
DROP TABLE EMP CASCADE CONSTRAINTS;
DROP TABLE ORD CASCADE CONSTRAINTS;
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE IMAGE CASCADE CONSTRAINTS;
DROP TABLE TITLE CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE LONGTEXT CASCADE CONSTRAINTS;
DROP TABLE INVENTORY CASCADE CONSTRAINTS;
DROP TABLE WAREHOUSE CASCADE CONSTRAINTS;
DROP TABLE PRACOWNICY CASCADE CONSTRAINTS;
set echo off

-- Zadanie 2
-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-05-29 22:38:05 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE



--- Utwórz tabelę player
CREATE TABLE player (
    player_id       NUMBER(7) NOT NULL,
    player_name     VARCHAR2(30) NOT NULL,
    player_health   INTEGER NOT NULL,
    player_mana     INTEGER NOT NULL,
    player_title    VARCHAR2(50)
    player_armor    VARCHAR2(50),
    player_damage   INTEGER,
    player_charisma INTEGER,
    player_money    NUMBER,
);

-- Dodaj klucz główny do tabeli player
ALTER TABLE player
    ADD CONSTRAINT player_pk
        PRIMARY KEY (player_id);

-- Utwórz tabelę dragon
CREATE TABLE dragon (
    monster_id       NUMBER(7) NOT NULL,
    monster_name     VARCHAR2(30) NOT NULL,
    monster_health   INTEGER NOT NULL,
    monster_damage   INTEGER NOT NULL,
    monster_armor    VARCHAR2(50),
    monster_loot     NUMBER,
    player_player_id NUMBER(7) NOT NULL
);

-- Dodaj klucz główny do tabeli dragon
ALTER TABLE dragon
    ADD CONSTRAINT dragon_pk
        PRIMARY KEY (monster_id);

-- Utwóz tabelę merchant
CREATE TABLE npc_merchant (
    npc_id           NUMBER(7) NOT NULL,
    npc_name         VARCHAR2(30) NOT NULL,
    npc_city         VARCHAR2(25) NOT NULL,
    npc_goods        VARCHAR2(100) NOT NULL,
    npc_money        NUMBER NOT NULL,
    npc_defense      VARCHAR2(50),
    npc_damage       INTEGER,
    player_player_id NUMBER(7) NOT NULL
);

-- Dodaj klucz główny do tabeli merchant
ALTER TABLE npc_merchant
    ADD CONSTRAINT npc_merchant_pk
        PRIMARY KEY (npc_id);

-- Dodaj klucz obcy do tabeli dragon
ALTER TABLE dragon
    ADD CONSTRAINT dragon_player_fk FOREIGN KEY (player_player_id)
        REFERENCES player (player_id);

-- Dodaj klucz obcy do tabeli merchant
ALTER TABLE npc_merchant
    ADD CONSTRAINT npc_merchant_player_fk FOREIGN KEY (player_player_id)
        REFERENCES player (player_id);

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

-- Zadanie 3
SELECT
    table_name  "Nazwa Tabeli"
FROM
    user_tables;

-- Zadanie 4
DESCRIBE player;
DESCRIBE dragon;
DESCRIBE npc_merchant;

-- Zadanie 5
SELECT
    column_name      "Nazwa Kolumny",
    constraint_name  "Nazwa Ograniczenia"
FROM
    User_cons_columns;

-- Zadanie 6
-- Metoda Kolumnowa
CREATE TABLE quest (
    quest_id            NUMBER(7) NOT NULL,
    quest_npc_id        NUMBER(7) NOT NULL,
    quest_description   VARCHAR2(50) NOT NULL,
    quest_objective     VARCHAR2(30) NOT NULL,
    quest_reward        INTEGER NOT NULL,
    PRIMARY KEY (quest_id),
    CONSTRAINT
        quest_quest_npc_id_fk
    REFERENCES
        npc_merchant(id));

-- Metoda Tablicowa
CREATE TABLE quest (
    quest_id            NUMBER(7) NOT NULL,
    quest_npc_id        NUMBER(7) NOT NULL,
    quest_description   VARCHAR2(50) NOT NULL,
    quest_objective     VARCHAR2(30) NOT NULL,
    quest_reward        INTEGER NOT NULL,
    PRIMARY KEY (quest_id),
    CONSTRAINT
        quest_quest_npc_id_fk
    FOREIGN KEY
        (npc_merchant_id)
    REFERENCES
        npc_merchant(id));

-- Metoda Alter Table
CREATE TABLE quest (
    quest_id            NUMBER(7) NOT NULL,
    quest_npc_id        NUMBER(7) NOT NULL,
    quest_description   VARCHAR2(50) NOT NULL,
    quest_objective     VARCHAR2(30) NOT NULL,
    quest_reward        INTEGER NOT NULL);

ALTER TABLE quest
    ADD CONSTRAINT
        quest_quest_npc_id_fk
    FOREIGN KEY
        (npc_merchant_id)
    REFERENCES
        npc_merchant(id);

-- Zadanie 7
ALTER TABLE player
    ADD CONSTRAINT unique_id
        UNIQUE (player_title);

ALTER TABLE player
    ADD CONSTRAINT player_title_title
        FOREIGN KEY (player_title)
            REFERENCES player_title(player_player_title);

-- Wprowadzenie i modyfikacja danych
-- Zadanie 8
INSERT INTO player VALUES(1, 'Tomek', 100, 200, NULL, 255, 300, 10, 1000);
INSERT INTO dragon VALUES(1, 'Mikolaj', 1000, 100, 200, 1000, 1);
INSERT INTO npc_merchant VALUES(1, 'Jakub', 'Lublin', 'Miecz', 200, , 20, 10, 1);

-- Zadanie 9
SELECT
    *
FROM
    player;

-- Zadanie 10
UPDATE player
    SET player_money = 1000
        WHERE player_name = 'Tomek';

-- Zadanie 11
SELECT
    *
FROM
    player;

-- Rozszerzanie bazy danych
-- Zadanie 12
CREATE TABLE emp(
    id                         NUMBER(7) CONSTRAINT emp_id_nn NOT NULL,
    last_name                  VARCHAR2(25) CONSTRAINT emp_last_name_nn NOT NULL,
    first_name                 VARCHAR2(25),
    userid                     VARCHAR2(8),
    start_date                 DATE,
    comments                   VARCHAR2(255),
    manager_id                 NUMBER(7),
    title                      VARCHAR2(25),
    dept_id                    NUMBER(7),
    salary                     NUMBER(11, 2),
    commission_pct             NUMBER(4, 2),
     CONSTRAINT emp_id_pk
        PRIMARY KEY (id),
     CONSTRAINT emp_userid_uk
        UNIQUE (userid),
     CONSTRAINT emp_commission_pct_ck
        CHECK (commission_pct IN (10, 12.5, 15, 17.5, 20)));

-- Wstawienie wartości do tabeli emp
INSERT INTO emp VALUES (
    1, 'Velasquez', 'Carmen', 'cvelasqu',
    to_date('03-MAR-1990 8:30', 'dd-mon-yyyy hh24:mi'), NULL, NULL, 'President',
    50, 2500, NULL);

INSERT INTO emp VALUES (
    2, 'Ngao', 'LaDoris', 'lngao',
    '08-MAR-1990', NULL, 1, 'VP, Operations',
    41, 1450, NULL);

INSERT INTO emp VALUES (
    3, 'Nagayama', 'Midori', 'mnagayam',
    '17-JUN-1991', NULL, 1, 'VP, Sales',
    31, 1400, NULL);

INSERT INTO emp VALUES (
    4, 'Quick-To-See', 'Mark', 'mquickto', 
    '07-APR-1990', NULL, 1, 'VP, Finance', 
    10, 1450, NULL);

INSERT INTO emp VALUES (
    5, 'Ropeburn', 'Audry', 'aropebur',
    '04-MAR-1990', NULL, 1, 'VP, Administration',
    50, 1550, NULL);

-- Zadanie 13
INSERT INTO player (
    first_name, id, dept_id, manager_id, null, null, dept_id, salary, title)
SELECT
    first_name, id, dept_id, manager_id, null, null, dept_id, salary, title
FROM
    emp;

-- Zadanie 14
SELECT
    *
FROM
    player;
