-- Zestaw 09 - Modelowanie bazy danych
-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-05-29 22:38:05 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE



--- Utwórz tabelę player
CREATE TABLE player (
    player_id       NUMBER(7) NOT NULL,
    player_name     VARCHAR2(30) NOT NULL,
    player_health   INTEGER NOT NULL,
    player_mana     INTEGER NOT NULL,
    player_title    VARCHAR2(50)
    player_armor    VARCHAR2(50),
    player_damage   INTEGER,
    player_charisma INTEGER,
    player_money    NUMBER,
);

-- Dodaj klucz główny do tabeli player
ALTER TABLE player
    ADD CONSTRAINT player_pk
        PRIMARY KEY (player_id);

-- Utwórz tabelę dragon
CREATE TABLE dragon (
    monster_id       NUMBER(7) NOT NULL,
    monster_name     VARCHAR2(30) NOT NULL,
    monster_health   INTEGER NOT NULL,
    monster_damage   INTEGER NOT NULL,
    monster_armor    VARCHAR2(50),
    monster_loot     NUMBER,
    player_player_id NUMBER(7) NOT NULL
);

-- Dodaj klucz główny do tabeli dragon
ALTER TABLE dragon
    ADD CONSTRAINT dragon_pk
        PRIMARY KEY (monster_id);

-- Utwóz tabelę merchant
CREATE TABLE npc_merchant (
    npc_id           NUMBER(7) NOT NULL,
    npc_name         VARCHAR2(30) NOT NULL,
    npc_city         VARCHAR2(25) NOT NULL,
    npc_goods        VARCHAR2(100) NOT NULL,
    npc_money        NUMBER NOT NULL,
    npc_defense      VARCHAR2(50),
    npc_damage       INTEGER,
    player_player_id NUMBER(7) NOT NULL
);

-- Dodaj klucz główny do tabeli merchant
ALTER TABLE npc_merchant
    ADD CONSTRAINT npc_merchant_pk
        PRIMARY KEY (npc_id);

-- Dodaj klucz obcy do tabeli dragon
ALTER TABLE dragon
    ADD CONSTRAINT dragon_player_fk FOREIGN KEY (player_player_id)
        REFERENCES player (player_id);

-- Dodaj klucz obcy do tabeli merchant
ALTER TABLE npc_merchant
    ADD CONSTRAINT npc_merchant_player_fk FOREIGN KEY (player_player_id)
        REFERENCES player (player_id);

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0